<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BeasiswasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('beasiswas')->delete();

        \DB::table('beasiswas')->insert(array(
            0 =>
                array(
                    'id' => 1,
                    'mahasiswa_id' => 1,
                    'kriteria_id' => 1,
                    'subkriteria_id' => 3,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 16:34:51',
                    'updated_at' => '2022-10-30 16:34:51',
                    'archived_at' => NULL,
                ),
            1 =>
                array(
                    'id' => 2,
                    'mahasiswa_id' => 1,
                    'kriteria_id' => 2,
                    'subkriteria_id' => 11,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 16:34:51',
                    'updated_at' => '2022-10-30 16:34:51',
                    'archived_at' => NULL,
                ),
            2 =>
                array(
                    'id' => 3,
                    'mahasiswa_id' => 1,
                    'kriteria_id' => 3,
                    'subkriteria_id' => 16,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 16:34:51',
                    'updated_at' => '2022-10-30 16:34:51',
                    'archived_at' => NULL,
                ),
            3 =>
                array(
                    'id' => 4,
                    'mahasiswa_id' => 1,
                    'kriteria_id' => 4,
                    'subkriteria_id' => 20,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 16:34:51',
                    'updated_at' => '2022-10-30 16:34:51',
                    'archived_at' => NULL,
                ),
            4 =>
                array(
                    'id' => 5,
                    'mahasiswa_id' => 1,
                    'kriteria_id' => 5,
                    'subkriteria_id' => 25,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 16:34:51',
                    'updated_at' => '2022-10-30 16:34:51',
                    'archived_at' => NULL,
                ),
            5 =>
                array(
                    'id' => 6,
                    'mahasiswa_id' => 1,
                    'kriteria_id' => 6,
                    'subkriteria_id' => 29,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 16:34:51',
                    'updated_at' => '2022-10-30 16:34:51',
                    'archived_at' => NULL,
                ),
            6 =>
                array(
                    'id' => 7,
                    'mahasiswa_id' => 1,
                    'kriteria_id' => 7,
                    'subkriteria_id' => 35,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 16:34:51',
                    'updated_at' => '2022-10-30 16:34:51',
                    'archived_at' => NULL,
                ),
            7 =>
                array(
                    'id' => 8,
                    'mahasiswa_id' => 1,
                    'kriteria_id' => 8,
                    'subkriteria_id' => 37,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 16:34:51',
                    'updated_at' => '2022-10-30 16:34:51',
                    'archived_at' => NULL,
                ),
            8 =>
                array(
                    'id' => 9,
                    'mahasiswa_id' => 1,
                    'kriteria_id' => 9,
                    'subkriteria_id' => 53,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 16:34:51',
                    'updated_at' => '2022-10-30 16:34:51',
                    'archived_at' => NULL,
                ),
            9 =>
                array(
                    'id' => 10,
                    'mahasiswa_id' => 1,
                    'kriteria_id' => 10,
                    'subkriteria_id' => 45,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 16:34:51',
                    'updated_at' => '2022-10-30 16:34:51',
                    'archived_at' => NULL,
                ),
            10 =>
                array(
                    'id' => 11,
                    'mahasiswa_id' => 1,
                    'kriteria_id' => 11,
                    'subkriteria_id' => 49,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 16:34:51',
                    'updated_at' => '2022-10-30 16:34:51',
                    'archived_at' => NULL,
                ),
            11 =>
                array(
                    'id' => 12,
                    'mahasiswa_id' => 2,
                    'kriteria_id' => 1,
                    'subkriteria_id' => 3,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 16:43:27',
                    'updated_at' => '2022-10-30 16:43:27',
                    'archived_at' => NULL,
                ),
            12 =>
                array(
                    'id' => 13,
                    'mahasiswa_id' => 2,
                    'kriteria_id' => 2,
                    'subkriteria_id' => 10,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 16:43:27',
                    'updated_at' => '2022-10-30 16:43:27',
                    'archived_at' => NULL,
                ),
            13 =>
                array(
                    'id' => 14,
                    'mahasiswa_id' => 2,
                    'kriteria_id' => 3,
                    'subkriteria_id' => 17,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 16:43:27',
                    'updated_at' => '2022-10-30 16:43:27',
                    'archived_at' => NULL,
                ),
            14 =>
                array(
                    'id' => 15,
                    'mahasiswa_id' => 2,
                    'kriteria_id' => 4,
                    'subkriteria_id' => 20,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 16:43:27',
                    'updated_at' => '2022-10-30 16:43:27',
                    'archived_at' => NULL,
                ),
            15 =>
                array(
                    'id' => 16,
                    'mahasiswa_id' => 2,
                    'kriteria_id' => 5,
                    'subkriteria_id' => 25,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 16:43:27',
                    'updated_at' => '2022-10-30 16:43:27',
                    'archived_at' => NULL,
                ),
            16 =>
                array(
                    'id' => 17,
                    'mahasiswa_id' => 2,
                    'kriteria_id' => 6,
                    'subkriteria_id' => 28,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 16:43:27',
                    'updated_at' => '2022-10-30 16:43:27',
                    'archived_at' => NULL,
                ),
            17 =>
                array(
                    'id' => 18,
                    'mahasiswa_id' => 2,
                    'kriteria_id' => 7,
                    'subkriteria_id' => 34,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 16:43:27',
                    'updated_at' => '2022-10-30 16:43:27',
                    'archived_at' => NULL,
                ),
            18 =>
                array(
                    'id' => 19,
                    'mahasiswa_id' => 2,
                    'kriteria_id' => 8,
                    'subkriteria_id' => 37,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 16:43:27',
                    'updated_at' => '2022-10-30 16:43:27',
                    'archived_at' => NULL,
                ),
            19 =>
                array(
                    'id' => 20,
                    'mahasiswa_id' => 2,
                    'kriteria_id' => 9,
                    'subkriteria_id' => 54,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 16:43:27',
                    'updated_at' => '2022-10-30 16:43:27',
                    'archived_at' => NULL,
                ),
            20 =>
                array(
                    'id' => 21,
                    'mahasiswa_id' => 2,
                    'kriteria_id' => 10,
                    'subkriteria_id' => 45,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 16:43:27',
                    'updated_at' => '2022-10-30 16:43:27',
                    'archived_at' => NULL,
                ),
            21 =>
                array(
                    'id' => 22,
                    'mahasiswa_id' => 2,
                    'kriteria_id' => 11,
                    'subkriteria_id' => 48,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 16:43:27',
                    'updated_at' => '2022-10-30 16:43:27',
                    'archived_at' => NULL,
                ),
            22 =>
                array(
                    'id' => 23,
                    'mahasiswa_id' => 3,
                    'kriteria_id' => 1,
                    'subkriteria_id' => 3,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:07:19',
                    'updated_at' => '2022-10-30 18:07:19',
                    'archived_at' => NULL,
                ),
            23 =>
                array(
                    'id' => 24,
                    'mahasiswa_id' => 3,
                    'kriteria_id' => 2,
                    'subkriteria_id' => 11,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:07:19',
                    'updated_at' => '2022-10-30 18:07:19',
                    'archived_at' => NULL,
                ),
            24 =>
                array(
                    'id' => 25,
                    'mahasiswa_id' => 3,
                    'kriteria_id' => 3,
                    'subkriteria_id' => 15,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:07:19',
                    'updated_at' => '2022-10-30 18:07:19',
                    'archived_at' => NULL,
                ),
            25 =>
                array(
                    'id' => 26,
                    'mahasiswa_id' => 3,
                    'kriteria_id' => 4,
                    'subkriteria_id' => 19,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:07:19',
                    'updated_at' => '2022-10-30 18:07:19',
                    'archived_at' => NULL,
                ),
            26 =>
                array(
                    'id' => 27,
                    'mahasiswa_id' => 3,
                    'kriteria_id' => 5,
                    'subkriteria_id' => 23,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:07:19',
                    'updated_at' => '2022-10-30 18:07:19',
                    'archived_at' => NULL,
                ),
            27 =>
                array(
                    'id' => 28,
                    'mahasiswa_id' => 3,
                    'kriteria_id' => 6,
                    'subkriteria_id' => 26,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:07:19',
                    'updated_at' => '2022-10-30 18:07:19',
                    'archived_at' => NULL,
                ),
            28 =>
                array(
                    'id' => 29,
                    'mahasiswa_id' => 3,
                    'kriteria_id' => 7,
                    'subkriteria_id' => 36,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:07:19',
                    'updated_at' => '2022-10-30 18:07:19',
                    'archived_at' => NULL,
                ),
            29 =>
                array(
                    'id' => 30,
                    'mahasiswa_id' => 3,
                    'kriteria_id' => 8,
                    'subkriteria_id' => 37,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:07:19',
                    'updated_at' => '2022-10-30 18:07:19',
                    'archived_at' => NULL,
                ),
            30 =>
                array(
                    'id' => 31,
                    'mahasiswa_id' => 3,
                    'kriteria_id' => 9,
                    'subkriteria_id' => 54,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:07:19',
                    'updated_at' => '2022-10-30 18:07:19',
                    'archived_at' => NULL,
                ),
            31 =>
                array(
                    'id' => 32,
                    'mahasiswa_id' => 3,
                    'kriteria_id' => 10,
                    'subkriteria_id' => 44,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:07:19',
                    'updated_at' => '2022-10-30 18:07:19',
                    'archived_at' => NULL,
                ),
            32 =>
                array(
                    'id' => 33,
                    'mahasiswa_id' => 3,
                    'kriteria_id' => 11,
                    'subkriteria_id' => 48,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:07:19',
                    'updated_at' => '2022-10-30 18:07:19',
                    'archived_at' => NULL,
                ),
            33 =>
                array(
                    'id' => 34,
                    'mahasiswa_id' => 4,
                    'kriteria_id' => 1,
                    'subkriteria_id' => 3,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:09:12',
                    'updated_at' => '2022-10-30 18:09:12',
                    'archived_at' => NULL,
                ),
            34 =>
                array(
                    'id' => 35,
                    'mahasiswa_id' => 4,
                    'kriteria_id' => 2,
                    'subkriteria_id' => 12,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:09:12',
                    'updated_at' => '2022-10-30 18:09:12',
                    'archived_at' => NULL,
                ),
            35 =>
                array(
                    'id' => 36,
                    'mahasiswa_id' => 4,
                    'kriteria_id' => 3,
                    'subkriteria_id' => 15,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:09:12',
                    'updated_at' => '2022-10-30 18:09:12',
                    'archived_at' => NULL,
                ),
            36 =>
                array(
                    'id' => 37,
                    'mahasiswa_id' => 4,
                    'kriteria_id' => 4,
                    'subkriteria_id' => 19,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:09:12',
                    'updated_at' => '2022-10-30 18:09:12',
                    'archived_at' => NULL,
                ),
            37 =>
                array(
                    'id' => 38,
                    'mahasiswa_id' => 4,
                    'kriteria_id' => 5,
                    'subkriteria_id' => 25,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:09:12',
                    'updated_at' => '2022-10-30 18:09:12',
                    'archived_at' => NULL,
                ),
            38 =>
                array(
                    'id' => 39,
                    'mahasiswa_id' => 4,
                    'kriteria_id' => 6,
                    'subkriteria_id' => 29,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:09:12',
                    'updated_at' => '2022-10-30 18:09:12',
                    'archived_at' => NULL,
                ),
            39 =>
                array(
                    'id' => 40,
                    'mahasiswa_id' => 4,
                    'kriteria_id' => 7,
                    'subkriteria_id' => 35,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:09:12',
                    'updated_at' => '2022-10-30 18:09:12',
                    'archived_at' => NULL,
                ),
            40 =>
                array(
                    'id' => 41,
                    'mahasiswa_id' => 4,
                    'kriteria_id' => 8,
                    'subkriteria_id' => 37,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:09:12',
                    'updated_at' => '2022-10-30 18:09:12',
                    'archived_at' => NULL,
                ),
            41 =>
                array(
                    'id' => 42,
                    'mahasiswa_id' => 4,
                    'kriteria_id' => 9,
                    'subkriteria_id' => 54,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:09:12',
                    'updated_at' => '2022-10-30 18:09:12',
                    'archived_at' => NULL,
                ),
            42 =>
                array(
                    'id' => 43,
                    'mahasiswa_id' => 4,
                    'kriteria_id' => 10,
                    'subkriteria_id' => 45,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:09:12',
                    'updated_at' => '2022-10-30 18:09:12',
                    'archived_at' => NULL,
                ),
            43 =>
                array(
                    'id' => 44,
                    'mahasiswa_id' => 4,
                    'kriteria_id' => 11,
                    'subkriteria_id' => 48,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:09:12',
                    'updated_at' => '2022-10-30 18:09:12',
                    'archived_at' => NULL,
                ),
            44 =>
                array(
                    'id' => 45,
                    'mahasiswa_id' => 5,
                    'kriteria_id' => 1,
                    'subkriteria_id' => 4,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:10:36',
                    'updated_at' => '2022-10-30 18:10:36',
                    'archived_at' => NULL,
                ),
            45 =>
                array(
                    'id' => 46,
                    'mahasiswa_id' => 5,
                    'kriteria_id' => 2,
                    'subkriteria_id' => 10,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:10:36',
                    'updated_at' => '2022-10-30 18:10:36',
                    'archived_at' => NULL,
                ),
            46 =>
                array(
                    'id' => 47,
                    'mahasiswa_id' => 5,
                    'kriteria_id' => 3,
                    'subkriteria_id' => 16,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:10:36',
                    'updated_at' => '2022-10-30 18:10:36',
                    'archived_at' => NULL,
                ),
            47 =>
                array(
                    'id' => 48,
                    'mahasiswa_id' => 5,
                    'kriteria_id' => 4,
                    'subkriteria_id' => 20,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:10:36',
                    'updated_at' => '2022-10-30 18:10:36',
                    'archived_at' => NULL,
                ),
            48 =>
                array(
                    'id' => 49,
                    'mahasiswa_id' => 5,
                    'kriteria_id' => 5,
                    'subkriteria_id' => 25,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:10:36',
                    'updated_at' => '2022-10-30 18:10:36',
                    'archived_at' => NULL,
                ),
            49 =>
                array(
                    'id' => 50,
                    'mahasiswa_id' => 5,
                    'kriteria_id' => 6,
                    'subkriteria_id' => 29,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:10:36',
                    'updated_at' => '2022-10-30 18:10:36',
                    'archived_at' => NULL,
                ),
            50 =>
                array(
                    'id' => 51,
                    'mahasiswa_id' => 5,
                    'kriteria_id' => 7,
                    'subkriteria_id' => 35,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:10:36',
                    'updated_at' => '2022-10-30 18:10:36',
                    'archived_at' => NULL,
                ),
            51 =>
                array(
                    'id' => 52,
                    'mahasiswa_id' => 5,
                    'kriteria_id' => 8,
                    'subkriteria_id' => 37,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:10:36',
                    'updated_at' => '2022-10-30 18:10:36',
                    'archived_at' => NULL,
                ),
            52 =>
                array(
                    'id' => 53,
                    'mahasiswa_id' => 5,
                    'kriteria_id' => 9,
                    'subkriteria_id' => 54,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:10:36',
                    'updated_at' => '2022-10-30 18:10:36',
                    'archived_at' => NULL,
                ),
            53 =>
                array(
                    'id' => 54,
                    'mahasiswa_id' => 5,
                    'kriteria_id' => 10,
                    'subkriteria_id' => 45,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:10:36',
                    'updated_at' => '2022-10-30 18:10:36',
                    'archived_at' => NULL,
                ),
            54 =>
                array(
                    'id' => 55,
                    'mahasiswa_id' => 5,
                    'kriteria_id' => 11,
                    'subkriteria_id' => 48,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:10:36',
                    'updated_at' => '2022-10-30 18:10:36',
                    'archived_at' => NULL,
                ),
            55 =>
                array(
                    'id' => 56,
                    'mahasiswa_id' => 6,
                    'kriteria_id' => 1,
                    'subkriteria_id' => 3,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:11:48',
                    'updated_at' => '2022-10-30 18:11:48',
                    'archived_at' => NULL,
                ),
            56 =>
                array(
                    'id' => 57,
                    'mahasiswa_id' => 6,
                    'kriteria_id' => 2,
                    'subkriteria_id' => 11,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:11:48',
                    'updated_at' => '2022-10-30 18:11:48',
                    'archived_at' => NULL,
                ),
            57 =>
                array(
                    'id' => 58,
                    'mahasiswa_id' => 6,
                    'kriteria_id' => 3,
                    'subkriteria_id' => 16,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:11:48',
                    'updated_at' => '2022-10-30 18:11:48',
                    'archived_at' => NULL,
                ),
            58 =>
                array(
                    'id' => 59,
                    'mahasiswa_id' => 6,
                    'kriteria_id' => 4,
                    'subkriteria_id' => 20,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:11:48',
                    'updated_at' => '2022-10-30 18:11:48',
                    'archived_at' => NULL,
                ),
            59 =>
                array(
                    'id' => 60,
                    'mahasiswa_id' => 6,
                    'kriteria_id' => 5,
                    'subkriteria_id' => 25,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:11:48',
                    'updated_at' => '2022-10-30 18:11:48',
                    'archived_at' => NULL,
                ),
            60 =>
                array(
                    'id' => 61,
                    'mahasiswa_id' => 6,
                    'kriteria_id' => 6,
                    'subkriteria_id' => 29,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:11:48',
                    'updated_at' => '2022-10-30 18:11:48',
                    'archived_at' => NULL,
                ),
            61 =>
                array(
                    'id' => 62,
                    'mahasiswa_id' => 6,
                    'kriteria_id' => 7,
                    'subkriteria_id' => 36,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:11:48',
                    'updated_at' => '2022-10-30 18:11:48',
                    'archived_at' => NULL,
                ),
            62 =>
                array(
                    'id' => 63,
                    'mahasiswa_id' => 6,
                    'kriteria_id' => 8,
                    'subkriteria_id' => 37,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:11:48',
                    'updated_at' => '2022-10-30 18:11:48',
                    'archived_at' => NULL,
                ),
            63 =>
                array(
                    'id' => 64,
                    'mahasiswa_id' => 6,
                    'kriteria_id' => 9,
                    'subkriteria_id' => 54,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:11:48',
                    'updated_at' => '2022-10-30 18:11:48',
                    'archived_at' => NULL,
                ),
            64 =>
                array(
                    'id' => 65,
                    'mahasiswa_id' => 6,
                    'kriteria_id' => 10,
                    'subkriteria_id' => 45,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:11:48',
                    'updated_at' => '2022-10-30 18:11:48',
                    'archived_at' => NULL,
                ),
            65 =>
                array(
                    'id' => 66,
                    'mahasiswa_id' => 6,
                    'kriteria_id' => 11,
                    'subkriteria_id' => 48,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:11:48',
                    'updated_at' => '2022-10-30 18:11:48',
                    'archived_at' => NULL,
                ),
            66 =>
                array(
                    'id' => 67,
                    'mahasiswa_id' => 7,
                    'kriteria_id' => 1,
                    'subkriteria_id' => 4,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:13:08',
                    'updated_at' => '2022-10-30 18:13:08',
                    'archived_at' => NULL,
                ),
            67 =>
                array(
                    'id' => 68,
                    'mahasiswa_id' => 7,
                    'kriteria_id' => 2,
                    'subkriteria_id' => 10,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:13:08',
                    'updated_at' => '2022-10-30 18:13:08',
                    'archived_at' => NULL,
                ),
            68 =>
                array(
                    'id' => 69,
                    'mahasiswa_id' => 7,
                    'kriteria_id' => 3,
                    'subkriteria_id' => 15,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:13:08',
                    'updated_at' => '2022-10-30 18:13:08',
                    'archived_at' => NULL,
                ),
            69 =>
                array(
                    'id' => 70,
                    'mahasiswa_id' => 7,
                    'kriteria_id' => 4,
                    'subkriteria_id' => 19,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:13:08',
                    'updated_at' => '2022-10-30 18:13:08',
                    'archived_at' => NULL,
                ),
            70 =>
                array(
                    'id' => 71,
                    'mahasiswa_id' => 7,
                    'kriteria_id' => 5,
                    'subkriteria_id' => 23,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:13:08',
                    'updated_at' => '2022-10-30 18:13:08',
                    'archived_at' => NULL,
                ),
            71 =>
                array(
                    'id' => 72,
                    'mahasiswa_id' => 7,
                    'kriteria_id' => 6,
                    'subkriteria_id' => 26,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:13:08',
                    'updated_at' => '2022-10-30 18:13:08',
                    'archived_at' => NULL,
                ),
            72 =>
                array(
                    'id' => 73,
                    'mahasiswa_id' => 7,
                    'kriteria_id' => 7,
                    'subkriteria_id' => 35,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:13:08',
                    'updated_at' => '2022-10-30 18:13:08',
                    'archived_at' => NULL,
                ),
            73 =>
                array(
                    'id' => 74,
                    'mahasiswa_id' => 7,
                    'kriteria_id' => 8,
                    'subkriteria_id' => 37,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:13:08',
                    'updated_at' => '2022-10-30 18:13:08',
                    'archived_at' => NULL,
                ),
            74 =>
                array(
                    'id' => 75,
                    'mahasiswa_id' => 7,
                    'kriteria_id' => 9,
                    'subkriteria_id' => 54,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:13:08',
                    'updated_at' => '2022-10-30 18:13:08',
                    'archived_at' => NULL,
                ),
            75 =>
                array(
                    'id' => 76,
                    'mahasiswa_id' => 7,
                    'kriteria_id' => 10,
                    'subkriteria_id' => 45,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:13:08',
                    'updated_at' => '2022-10-30 18:13:08',
                    'archived_at' => NULL,
                ),
            76 =>
                array(
                    'id' => 77,
                    'mahasiswa_id' => 7,
                    'kriteria_id' => 11,
                    'subkriteria_id' => 48,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:13:08',
                    'updated_at' => '2022-10-30 18:13:08',
                    'archived_at' => NULL,
                ),
            77 =>
                array(
                    'id' => 78,
                    'mahasiswa_id' => 8,
                    'kriteria_id' => 1,
                    'subkriteria_id' => 3,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:14:45',
                    'updated_at' => '2022-10-30 18:14:45',
                    'archived_at' => NULL,
                ),
            78 =>
                array(
                    'id' => 79,
                    'mahasiswa_id' => 8,
                    'kriteria_id' => 2,
                    'subkriteria_id' => 10,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:14:45',
                    'updated_at' => '2022-10-30 18:14:45',
                    'archived_at' => NULL,
                ),
            79 =>
                array(
                    'id' => 80,
                    'mahasiswa_id' => 8,
                    'kriteria_id' => 3,
                    'subkriteria_id' => 17,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:14:45',
                    'updated_at' => '2022-10-30 18:14:45',
                    'archived_at' => NULL,
                ),
            80 =>
                array(
                    'id' => 81,
                    'mahasiswa_id' => 8,
                    'kriteria_id' => 4,
                    'subkriteria_id' => 20,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:14:45',
                    'updated_at' => '2022-10-30 18:14:45',
                    'archived_at' => NULL,
                ),
            81 =>
                array(
                    'id' => 82,
                    'mahasiswa_id' => 8,
                    'kriteria_id' => 5,
                    'subkriteria_id' => 25,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:14:45',
                    'updated_at' => '2022-10-30 18:14:45',
                    'archived_at' => NULL,
                ),
            82 =>
                array(
                    'id' => 83,
                    'mahasiswa_id' => 8,
                    'kriteria_id' => 6,
                    'subkriteria_id' => 28,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:14:45',
                    'updated_at' => '2022-10-30 18:14:45',
                    'archived_at' => NULL,
                ),
            83 =>
                array(
                    'id' => 84,
                    'mahasiswa_id' => 8,
                    'kriteria_id' => 7,
                    'subkriteria_id' => 35,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:14:45',
                    'updated_at' => '2022-10-30 18:14:45',
                    'archived_at' => NULL,
                ),
            84 =>
                array(
                    'id' => 85,
                    'mahasiswa_id' => 8,
                    'kriteria_id' => 8,
                    'subkriteria_id' => 37,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:14:45',
                    'updated_at' => '2022-10-30 18:14:45',
                    'archived_at' => NULL,
                ),
            85 =>
                array(
                    'id' => 86,
                    'mahasiswa_id' => 8,
                    'kriteria_id' => 9,
                    'subkriteria_id' => 50,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:14:45',
                    'updated_at' => '2022-10-30 18:14:45',
                    'archived_at' => NULL,
                ),
            86 =>
                array(
                    'id' => 87,
                    'mahasiswa_id' => 8,
                    'kriteria_id' => 10,
                    'subkriteria_id' => 45,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:14:45',
                    'updated_at' => '2022-10-30 18:14:45',
                    'archived_at' => NULL,
                ),
            87 =>
                array(
                    'id' => 88,
                    'mahasiswa_id' => 8,
                    'kriteria_id' => 11,
                    'subkriteria_id' => 48,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:14:45',
                    'updated_at' => '2022-10-30 18:14:45',
                    'archived_at' => NULL,
                ),
            88 =>
                array(
                    'id' => 89,
                    'mahasiswa_id' => 9,
                    'kriteria_id' => 1,
                    'subkriteria_id' => 3,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:16:13',
                    'updated_at' => '2022-10-30 18:16:13',
                    'archived_at' => NULL,
                ),
            89 =>
                array(
                    'id' => 90,
                    'mahasiswa_id' => 9,
                    'kriteria_id' => 2,
                    'subkriteria_id' => 10,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:16:13',
                    'updated_at' => '2022-10-30 18:16:13',
                    'archived_at' => NULL,
                ),
            90 =>
                array(
                    'id' => 91,
                    'mahasiswa_id' => 9,
                    'kriteria_id' => 3,
                    'subkriteria_id' => 17,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:16:13',
                    'updated_at' => '2022-10-30 18:16:13',
                    'archived_at' => NULL,
                ),
            91 =>
                array(
                    'id' => 92,
                    'mahasiswa_id' => 9,
                    'kriteria_id' => 4,
                    'subkriteria_id' => 20,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:16:13',
                    'updated_at' => '2022-10-30 18:16:13',
                    'archived_at' => NULL,
                ),
            92 =>
                array(
                    'id' => 93,
                    'mahasiswa_id' => 9,
                    'kriteria_id' => 5,
                    'subkriteria_id' => 25,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:16:13',
                    'updated_at' => '2022-10-30 18:16:13',
                    'archived_at' => NULL,
                ),
            93 =>
                array(
                    'id' => 94,
                    'mahasiswa_id' => 9,
                    'kriteria_id' => 6,
                    'subkriteria_id' => 28,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:16:13',
                    'updated_at' => '2022-10-30 18:16:13',
                    'archived_at' => NULL,
                ),
            94 =>
                array(
                    'id' => 95,
                    'mahasiswa_id' => 9,
                    'kriteria_id' => 7,
                    'subkriteria_id' => 35,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:16:13',
                    'updated_at' => '2022-10-30 18:16:13',
                    'archived_at' => NULL,
                ),
            95 =>
                array(
                    'id' => 96,
                    'mahasiswa_id' => 9,
                    'kriteria_id' => 8,
                    'subkriteria_id' => 37,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:16:13',
                    'updated_at' => '2022-10-30 18:16:13',
                    'archived_at' => NULL,
                ),
            96 =>
                array(
                    'id' => 97,
                    'mahasiswa_id' => 9,
                    'kriteria_id' => 9,
                    'subkriteria_id' => 51,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:16:13',
                    'updated_at' => '2022-10-30 18:27:47',
                    'archived_at' => NULL,
                ),
            97 =>
                array(
                    'id' => 98,
                    'mahasiswa_id' => 9,
                    'kriteria_id' => 10,
                    'subkriteria_id' => 45,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:16:13',
                    'updated_at' => '2022-10-30 18:16:13',
                    'archived_at' => NULL,
                ),
            98 =>
                array(
                    'id' => 99,
                    'mahasiswa_id' => 9,
                    'kriteria_id' => 11,
                    'subkriteria_id' => 48,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:16:13',
                    'updated_at' => '2022-10-30 18:16:13',
                    'archived_at' => NULL,
                ),
            99 =>
                array(
                    'id' => 100,
                    'mahasiswa_id' => 10,
                    'kriteria_id' => 1,
                    'subkriteria_id' => 4,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:21:38',
                    'updated_at' => '2022-10-30 18:21:38',
                    'archived_at' => NULL,
                ),
            100 =>
                array(
                    'id' => 101,
                    'mahasiswa_id' => 10,
                    'kriteria_id' => 2,
                    'subkriteria_id' => 9,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:21:38',
                    'updated_at' => '2022-10-30 18:21:38',
                    'archived_at' => NULL,
                ),
            101 =>
                array(
                    'id' => 102,
                    'mahasiswa_id' => 10,
                    'kriteria_id' => 3,
                    'subkriteria_id' => 15,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:21:38',
                    'updated_at' => '2022-10-30 18:21:38',
                    'archived_at' => NULL,
                ),
            102 =>
                array(
                    'id' => 103,
                    'mahasiswa_id' => 10,
                    'kriteria_id' => 4,
                    'subkriteria_id' => 19,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:21:38',
                    'updated_at' => '2022-10-30 18:21:38',
                    'archived_at' => NULL,
                ),
            103 =>
                array(
                    'id' => 104,
                    'mahasiswa_id' => 10,
                    'kriteria_id' => 5,
                    'subkriteria_id' => 25,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:21:38',
                    'updated_at' => '2022-10-30 18:21:38',
                    'archived_at' => NULL,
                ),
            104 =>
                array(
                    'id' => 105,
                    'mahasiswa_id' => 10,
                    'kriteria_id' => 6,
                    'subkriteria_id' => 30,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:21:38',
                    'updated_at' => '2022-10-30 18:21:38',
                    'archived_at' => NULL,
                ),
            105 =>
                array(
                    'id' => 106,
                    'mahasiswa_id' => 10,
                    'kriteria_id' => 7,
                    'subkriteria_id' => 35,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:21:38',
                    'updated_at' => '2022-10-30 18:21:38',
                    'archived_at' => NULL,
                ),
            106 =>
                array(
                    'id' => 107,
                    'mahasiswa_id' => 10,
                    'kriteria_id' => 8,
                    'subkriteria_id' => 38,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:21:38',
                    'updated_at' => '2022-10-30 18:21:38',
                    'archived_at' => NULL,
                ),
            107 =>
                array(
                    'id' => 108,
                    'mahasiswa_id' => 10,
                    'kriteria_id' => 9,
                    'subkriteria_id' => 50,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:21:38',
                    'updated_at' => '2022-10-30 18:21:38',
                    'archived_at' => NULL,
                ),
            108 =>
                array(
                    'id' => 109,
                    'mahasiswa_id' => 10,
                    'kriteria_id' => 10,
                    'subkriteria_id' => 45,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:21:38',
                    'updated_at' => '2022-10-30 18:21:38',
                    'archived_at' => NULL,
                ),
            109 =>
                array(
                    'id' => 110,
                    'mahasiswa_id' => 10,
                    'kriteria_id' => 11,
                    'subkriteria_id' => 48,
                    'tahun_akademik_id' => 1,
                    'created_at' => '2022-10-30 18:21:38',
                    'updated_at' => '2022-10-30 18:21:38',
                    'archived_at' => NULL,
                ),
        ));


    }
}
